### ISSUE TITLE
Hygiene and names of type/lifetime parameters

### ISSUE THREAD

**Issue by LukasKalbertodt** [KodrAus/auto_impl#12]
So we need our own type parameter (and lifetime parameter in case of `&` and `&mut`). Right now they have the beautiful names `__AutoImplProxyT` and `__auto_impl_proxy_lifetime`. This is done because the part of proc macro API that has now been stabilized [doesn't include def site hygiene](https://doc.rust-lang.org/nightly/proc_macro/struct.Span.html#method.def_site) but only call site hygiene. Meaning: the names we use are in the same "namespace" as all names of the user. And to avoid having naming conflicts we use these terrible names.

This is far from optimal. For example, these names pop up in the documentation and error messages:

![image](https://user-images.githubusercontent.com/7419664/42967174-b623e3f0-8b9f-11e8-844e-ee45efab022e.png)

... this ain't pretty.

---

My idea to solve this problem is to do a bit more work in `auto_impl` and choose a name that is not already taken. Luckily, we can inspect all other parameters that will be in scope and choose a name different from all of them. As far as I can tell, that's the best solution for good docs and errors. In that case we need to decide:

1. If `T`/`'a` is already taken, how to choose the name? `U` and `'b`? And then? Or fallback to our terrible name from above? 
2. Should we do something different if compiled on nightly, like using def site hygiene and always use `T` and `'a`?
3. Should we simply use the new anonymous/in-band lifetimes (`impl<T> Foo for &'_ T`) to get rid of our lifetime parameter?

My (not strong) opinion right now:
1. Use `U` and `'b` and keep using the remaining alphabet. If we exhausted the alphabet, we can fallback to the terrible names. The latter will probably never happen.
2. If we have a solution for stable, I think we don't need to use def site hygiene on nightly. `impl<T, T>` will look strange in the documentation, even if the compiler knows that the two `T`s are different.
3.  I think I'm in favor of using the anonymous lifetime, because proc-macros and in band lifetimes will be stabilized at roughly the same time, so we don't really lose "users" by requiring a new compiler version.

**Comment by KodrAus** [comment]
I think I'm in favour of a scheme to choose 'reasonable' generic parameter names too. Maybe it's not as bulletproof as def-site-hygiene, but it keeps the generated code closer to what you'd write by hand. Using in-band lifetimes when they're available also sounds like a good thing to do to get rid of our lifetime altogether.

**Comment by LukasKalbertodt** [comment]
Great! Then I'll work on this after I finished the testing work.
