### ISSUE TITLE
Should we add `#[inline]` to generated methods?

### ISSUE THREAD

**Issue by LukasKalbertodt** [KodrAus/auto_impl#20]
The methods we generate in the `impl` blocks are super simple and just call another function. Therefore one might want to add `#[inline]` or `#[inline(always)]` to those methods. However, in C++ land I learned that the programmer usually is way dumber than the compiler and that one should just let the compiler do its thing most of the time.

I'm not sure what we should do here.

**Comment by KodrAus** [comment]
I think we should be ok without an `#[inline]` attribute because the impls generated are all generic so should be candidates for inlining across crates already.

**Comment by LukasKalbertodt** [comment]
Good point. So I'll close this. If someone actual encounters problems due to this, we can reopen.
